---
- hosts: tomcat  
  become: True
  tasks:
    - name: Deploy to tomcat
      copy:
        src: /var/lib/jenkins/workspace/webapp-ci-cd-pipeline/target/*.war 
        dest: /opt/tomcat10/webapps/WebApp.war
...
