---
- name: deploy war
  hosts: tomcat  
  tasks:
    - name: copy the war file
      copy:
        src: /var/lib/jenkins/workspace/webapp-ci-cd-pipeline/target/WebApp.war 
        dest: /opt/tomcat10/webapps/
