---
- hosts: tomcat  
  become: True
  tasks:
    - name: Deploy a war file
      copy:
        src: /var/lib/jenkins/workspace/webapp-ci-cd-pipeline/target/*.war 
        dest: ubuntu@172.31.89.218:/opt/tomcat10/webapps/WebApp.war
